### ISSUE TITLE
内容适配窗口问题

### ISSUE THREAD

**Issue by lxb6476** [xnng/bash#2]
执行命令后，如果输出内容过长，会自动换行，但是改变窗口大小后，内容不会跟随窗口适配，请问有解决方案吗？
出现的情况如下：
![image](https://user-images.githubusercontent.com/26701345/66883057-1f292580-efff-11e9-9eb8-12b686107afb.png)

**Comment by xnng** [comment]
可以考虑使用 Windows Terminal，将 Git Bash 添加到 Windows Terminal 中，让其渲染字符，效果会更好。
